# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.NonModal)
        Form.resize(321, 286)
        Form.setMouseTracking(False)
        Form.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        Form.setStyleSheet("background-color: rgb(59, 59, 59);\n"
"color: rgb(170, 255, 0);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.labelM = QtWidgets.QLabel(Form)
        self.labelM.setMinimumSize(QtCore.QSize(30, 0))
        self.labelM.setStyleSheet("color: rgb(255, 170, 0);")
        self.labelM.setObjectName("labelM")
        self.horizontalLayout.addWidget(self.labelM)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEditD = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditD.sizePolicy().hasHeightForWidth())
        self.lineEditD.setSizePolicy(sizePolicy)
        self.lineEditD.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditD.setMaximumSize(QtCore.QSize(30, 16777215))
        self.lineEditD.setStyleSheet("color: rgb(255, 170, 0);")
        self.lineEditD.setMaxLength(100)
        self.lineEditD.setObjectName("lineEditD")
        self.horizontalLayout.addWidget(self.lineEditD)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.lineEditH = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditH.sizePolicy().hasHeightForWidth())
        self.lineEditH.setSizePolicy(sizePolicy)
        self.lineEditH.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEditH.setMaximumSize(QtCore.QSize(30, 16777215))
        self.lineEditH.setStyleSheet("color: rgb(255, 170, 0);")
        self.lineEditH.setObjectName("lineEditH")
        self.horizontalLayout.addWidget(self.lineEditH)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.labelDd = QtWidgets.QLabel(self.groupBox)
        self.labelDd.setMinimumSize(QtCore.QSize(30, 0))
        self.labelDd.setStyleSheet("color: rgb(255, 170, 0);")
        self.labelDd.setObjectName("labelDd")
        self.horizontalLayout_2.addWidget(self.labelDd)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.labelHd = QtWidgets.QLabel(self.groupBox)
        self.labelHd.setMinimumSize(QtCore.QSize(50, 0))
        self.labelHd.setStyleSheet("color: rgb(255, 170, 0);")
        self.labelHd.setObjectName("labelHd")
        self.horizontalLayout_2.addWidget(self.labelHd)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.labelAd = QtWidgets.QLabel(self.groupBox)
        self.labelAd.setMinimumSize(QtCore.QSize(40, 0))
        self.labelAd.setStyleSheet("color: rgb(255, 170, 0);")
        self.labelAd.setObjectName("labelAd")
        self.horizontalLayout_2.addWidget(self.labelAd)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_3.addWidget(self.label_11)
        self.labelDl = QtWidgets.QLabel(self.groupBox_2)
        self.labelDl.setMinimumSize(QtCore.QSize(30, 0))
        self.labelDl.setStyleSheet("color: rgb(255, 170, 0);")
        self.labelDl.setObjectName("labelDl")
        self.horizontalLayout_3.addWidget(self.labelDl)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_3.addWidget(self.label_16)
        self.labelHl = QtWidgets.QLabel(self.groupBox_2)
        self.labelHl.setMinimumSize(QtCore.QSize(50, 0))
        self.labelHl.setStyleSheet("color: rgb(255, 170, 0);")
        self.labelHl.setObjectName("labelHl")
        self.horizontalLayout_3.addWidget(self.labelHl)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_3.addWidget(self.label_12)
        self.labelAl = QtWidgets.QLabel(self.groupBox_2)
        self.labelAl.setMinimumSize(QtCore.QSize(40, 0))
        self.labelAl.setStyleSheet("color: rgb(255, 170, 0);")
        self.labelAl.setObjectName("labelAl")
        self.horizontalLayout_3.addWidget(self.labelAl)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.progressBarA = QtWidgets.QProgressBar(Form)
        self.progressBarA.setStyleSheet("color: rgb(255, 170, 0);")
        self.progressBarA.setProperty("value", 24)
        self.progressBarA.setTextVisible(True)
        self.progressBarA.setOrientation(QtCore.Qt.Horizontal)
        self.progressBarA.setInvertedAppearance(False)
        self.progressBarA.setObjectName("progressBarA")
        self.verticalLayout.addWidget(self.progressBarA)
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_4.addWidget(self.label_10)
        self.labelTb = QtWidgets.QLabel(self.groupBox_3)
        self.labelTb.setMinimumSize(QtCore.QSize(40, 0))
        self.labelTb.setStyleSheet("color: rgb(255, 170, 0);")
        self.labelTb.setObjectName("labelTb")
        self.horizontalLayout_4.addWidget(self.labelTb)
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.labelTe = QtWidgets.QLabel(self.groupBox_3)
        self.labelTe.setMinimumSize(QtCore.QSize(40, 0))
        self.labelTe.setStyleSheet("color: rgb(255, 170, 0);")
        self.labelTe.setObjectName("labelTe")
        self.horizontalLayout_4.addWidget(self.labelTe)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.labelTl = QtWidgets.QLabel(self.groupBox_3)
        self.labelTl.setMinimumSize(QtCore.QSize(40, 0))
        self.labelTl.setStyleSheet("color: rgb(255, 170, 0);")
        self.labelTl.setObjectName("labelTl")
        self.horizontalLayout_4.addWidget(self.labelTl)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.progressBarT = QtWidgets.QProgressBar(Form)
        self.progressBarT.setStyleSheet("color: rgb(255, 170, 0);")
        self.progressBarT.setProperty("value", 24)
        self.progressBarT.setObjectName("progressBarT")
        self.verticalLayout.addWidget(self.progressBarT)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Рабочее время"))
        self.label.setText(_translate("Form", "Месяц"))
        self.labelM.setText(_translate("Form", "1"))
        self.label_2.setText(_translate("Form", "Дней"))
        self.lineEditD.setText(_translate("Form", "1"))
        self.label_3.setText(_translate("Form", "Часов"))
        self.lineEditH.setText(_translate("Form", "1"))
        self.groupBox.setTitle(_translate("Form", "Отработано"))
        self.label_4.setText(_translate("Form", "Дней"))
        self.labelDd.setText(_translate("Form", "0"))
        self.label_5.setText(_translate("Form", "Часов"))
        self.labelHd.setText(_translate("Form", "0"))
        self.label_7.setText(_translate("Form", "Среднее"))
        self.labelAd.setText(_translate("Form", "0"))
        self.groupBox_2.setTitle(_translate("Form", "Осталось"))
        self.label_11.setText(_translate("Form", "Дней "))
        self.labelDl.setText(_translate("Form", "0"))
        self.label_16.setText(_translate("Form", "Часов"))
        self.labelHl.setText(_translate("Form", "0"))
        self.label_12.setText(_translate("Form", "Среднее"))
        self.labelAl.setText(_translate("Form", "0"))
        self.progressBarA.setFormat(_translate("Form", "%p%"))
        self.groupBox_3.setTitle(_translate("Form", "Сегодня"))
        self.label_10.setText(_translate("Form", "Приход"))
        self.labelTb.setText(_translate("Form", "0"))
        self.label_8.setText(_translate("Form", "Уход"))
        self.labelTe.setText(_translate("Form", "0"))
        self.label_6.setText(_translate("Form", "Осталось"))
        self.labelTl.setText(_translate("Form", "0"))
